# Generated by Django 4.0 on 2022-01-03 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('1', 'Pending'), ('2', 'In Progress'), ('3', 'Completed')], default='1', max_length=20),
        ),
    ]
