on:
  pull_request:
  issue_comment:
jobs:
  pr_agent_job:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: write
    name: Run pr agent on every pull request, respond to user comments
    steps:
      - name: PR Agent action step
        id: pragent
        uses: nandantws/pr-agent@main
        env:
          OPENAI_KEY: ${{ secrets.YNCxEaPGD8lsMR-SYe0eE1Ln-LoOLfpcxeUfpl3RrTuk2fbJluzbH8wd4V8raDTN6D15QaMofDdMZHQCkHGuySo_zPv76kn-EnM2r27XJe6qjKUT5P1qBELpZRML5CL4 }}
          GITHUB_TOKEN: ${{ secrets.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 }}
